# Generated by Django 4.1 on 2022-08-26 04:11

from django.db import migrations
import server.apps.blog.blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='body',
            field=wagtail.fields.StreamField([('h1', wagtail.blocks.CharBlock()), ('h2', wagtail.blocks.CharBlock()), ('paragraph', wagtail.blocks.RichTextBlock()), ('image_text', wagtail.blocks.StructBlock([('reverse', wagtail.blocks.BooleanBlock(required=False)), ('text', wagtail.blocks.RichTextBlock()), ('image', server.apps.blog.blocks.CustomImageChooserBlock())])), ('image_carousel', wagtail.blocks.ListBlock(server.apps.blog.blocks.CustomImageChooserBlock())), ('thumbnail_gallery', wagtail.blocks.ListBlock(server.apps.blog.blocks.CustomImageChooserBlock()))], blank=True, use_json_field=None),
        ),
    ]
